In [1]:
import os
import sympy as sp
import numpy as np
from multipie.core.model_analyzer import ModelAnalyzer

MODEL_DIR = os.getcwd() + "/model/"
Te = {
    "samb": {
        "model": "Te",
        "parameter": {
            "z4": 0.0, # chiral CEF
            "z6":1.0, # nonchiral hopping
            "z8":0.2, # chiral hopping
        },
        "samb_figure": False,
        "k_multipole":True,
    },
    "wannier": {  
        "seedname": "Te",  # read seedname.win, seedname.nnkp, (seedname.mmn, seedname.spn, seedname.uHu, seedname.uIu ...).
        # "ket_wannier": [
        #     ['A', 1, 1, 2, 'pz'],
        #     ['A', 1, 1, 0, 'px'],
        #     ['A', 1, 1, 1, 'py'],
        #     ['A', 3, 1, 2, 'pz'],
        #     ['A', 3, 1, 0, 'px'],
        #     ['A', 3, 1, 1, 'py'],
        #     ['A', 2, 1, 2, 'pz'],
        #     ['A', 2, 1, 0, 'px'],
        #     ['A', 2, 1, 1, 'py'],
        # ],
        "hr_file": "Te_hr_cw.dat",  # read seedname_hr.dat.
    },
    "output": {
        "dispersion": {
            "k_path":"",
            "local":["Lz"],
        },
    },
}

ma = ModelAnalyzer(N1=200,topdir=MODEL_DIR, verbose=True)
ma.analyze(Te)

load binary from '/Users/ro/GitHub/MultiPie/others/tests/model/Te/Te.pkl'.
"""
Model: Te
* Group: D3^4
* SAMB selection: {'X': ['Q', 'G'], 'l': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], 'Gamma': ['A1', 'A2', 'E'], 's': [0, 1]}
* atomic selection: {'X': ['Q', 'G', 'M', 'T'], 'l': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], 'Gamma': ['A1', 'A2', 'E'], 's': [0, 1]}
* site-cluster selection: {'l': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], 'Gamma': ['A1', 'A2', 'E'], 'X': ['Q', 'G', 'M', 'T'], 's': [0, 1]}
* bond-cluster selection: {'X': ['Q', 'G', 'M', 'T'], 'l': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], 'Gamma': ['A1', 'A2', 'E'], 's': [0, 1]}
  45 (all 45) basis set
"""
save hr to '/Users/ro/GitHub/MultiPie/others/tests/model/Te/Te_hr.dat'.
save z to '/Users/ro/GitHub/MultiPie/others/tests/model/Te/Te_z.py'.
save matrix to '/Users/ro/GitHub/MultiPie/others/tests/model/Te/Te_matrix.py'.
save var to '/Users/ro/GitHub/MultiPie/others/tests/model/Te/Te_var.py'.
save k-multipole to '/Users/ro/GitHub/Mu

/Users/ro/.pyenv/versions/3.12.7/lib/python3.12/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['std_lattice']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/Users/ro/.pyenv/versions/3.12.7/lib/python3.12/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['std_positions']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/Users/ro/.pyenv/versions/3.12.7/lib/python3.12/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['std_types']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/Users/ro/.pyenv/versions/3.12.7/lib/python3.12/site-packages/spglib/spglib.py:115: DeprecationWarning: dict interface (SpglibDataset['number']) is deprecated.Use attribute interface ({self.__class__.__name__}.{key}) instead
  warnings.warn(
/Users/ro/.pyenv/

save dispersion to '/Users/ro/GitHub/MultiPie/others/tests/model/Te/output/Te_dispersion.txt'.


In [2]:
ma["wannier"]["info"]

{'A': [[4.458, 0.0, 0.0], [-2.2290001, 3.8607414, 0.0], [0.0, 0.0, 5.925]],
 'B': [[1.409418, 0.8137278, 0.0],
  [0.0, 1.6274556, 0.0],
  [0.0, 0.0, 1.0604532]],
 'ket': [['A', 1, 1, 0, 'px'],
  ['A', 1, 1, 1, 'py'],
  ['A', 1, 1, 2, 'pz'],
  ['A', 2, 1, 0, 'px'],
  ['A', 2, 1, 1, 'py'],
  ['A', 2, 1, 2, 'pz'],
  ['A', 3, 1, 0, 'px'],
  ['A', 3, 1, 1, 'py'],
  ['A', 3, 1, 2, 'pz']],
 'num_wann': 9,
 'atoms_frac': [array([0.274     , 0.        , 0.33333333]),
  array([0.274     , 0.        , 0.33333333]),
  array([0.274     , 0.        , 0.33333333]),
  array([0.        , 0.274     , 0.66666667]),
  array([0.        , 0.274     , 0.66666667]),
  array([0.        , 0.274     , 0.66666667]),
  array([0.726, 0.726, 0.   ]),
  array([0.726, 0.726, 0.   ]),
  array([0.726, 0.726, 0.   ])],
 'atoms_cart': [array([1.221492, 0.      , 1.975   ]),
  array([1.221492, 0.      , 1.975   ]),
  array([1.221492, 0.      , 1.975   ]),
  array([-0.61074603,  1.05784314,  3.95      ]),
  array([-0.610746

In [3]:
ma["wannier"]["ket"] == ma.model["full_matrix"]["ket"]

True

In [4]:
ma["wannier"]["z_j"]

{'z1': np.float64(13.96348060333332),
 'z2': np.float64(0.2547402572367805),
 'z3': np.float64(0.17360326240196594),
 'z4': np.float64(-0.33496460153367136),
 'z5': np.float64(1.3318490979344944),
 'z6': np.float64(1.1485136753333314),
 'z7': np.float64(-2.5809073271406806),
 'z8': np.float64(0.012196357484102638),
 'z9': np.float64(4.824502465140611),
 'z10': np.float64(0.017690825163573898),
 'z11': np.float64(1.1535265638518144e-08),
 'z12': np.float64(-1.373149814687391e-08),
 'z13': np.float64(7.73476102611248e-09),
 'z14': np.float64(3.6633867050994695e-09),
 'z15': np.float64(1.5698089356197542e-09),
 'z16': np.float64(-1.6336523667837e-05),
 'z17': np.float64(-3.61258912231488e-05),
 'z18': np.float64(0.00015764246785201705),
 'z19': np.float64(-6.620350613162351e-06),
 'z20': np.float64(-0.0012786338906818143),
 'z21': np.float64(-7.902277875115882e-07),
 'z22': np.float64(0.0018609916671135096),
 'z23': np.float64(-4.57222054755374e-06),
 'z24': np.float64(-0.0001449418532580